### ISSUE TITLE
重加qq群失败,请求给你的小灰增加"加入irc频道(perl学习交流群)连通"特性

### ISSUE THREAD

**Issue by wxg4net** [sjdy521/pfqq#6]
加群失败,可能是qq版本太低.

**Comment by sjdy521** [comment]
有什么免费的irc服务器可以使用吗


发自网易邮箱大师
在2015年05月03日 09:12，wxg 写道:

加群失败,可能是qq版本太低.

**Comment by wxg4net** [comment]
freenode 的 irc房间即可 类似 已经注册的 #perl-cn 频道.

**Comment by sjdy521** [comment]
五一回去加一下这个功能


发自网易邮箱大师
在2015年05月03日 12:51，wxg 写道:

freenode 的 irc房间即可 类似 已经注册的 #perl-cn 频道.

**Comment by sjdy521** [comment]
通过Webqq::Client::Plugin::IrcSync插件实现
群[PERL学习交流]当前的IRC频道为irc.freenode.net#ChinaPerl
